let currentLang = localStorage.getItem('gmaLang') || 'fr';
let mapInstance = null;
let activePhenotype = 'all';
let siteSearch = '';
let siteStatus = 'all';

const i18n = {
  fr: {
    brand:'GMA — Observatoire du Capital Vivant', nav_home:'Accueil', nav_pres:'Présentation', nav_formulas:'Formules', nav_map:'Carte SIG', nav_calc:'Calculateur BRₘ', nav_delphi:'Delphi', nav_contact:'Contact',
    hero_title_top:'Observatoire International GMA', hero_title_bottom:'Living Capital', hero_kicker:'GLOBAL MESOLOGY ALERT', hero_sub:'CAPITAL VIVANT · SURVEILLANCE · ANALYSE · PROTECTION',
    cta_calc:'Calculer BRₘ →', cta_delphi:'Contribuer bénévolement', cta_map:'Suivi des sites',
    stat1:'Sites formalisés', stat2:'Sites à valider', stat3:'BRₘ max (El Bayadh–Djelfa)', stat4:'Seuil heuristique',
    home_kicker:'GMA · lecture rapide', home_operational:'CADRE OPÉRATIONNEL', home_concept:'Du concept au signal territorial', home_concept_text:'Le site ne présente pas seulement le BRₘ : il montre comment passer de la pression et de la résilience à une décision d’investigation, puis à une validation experte.', home_step1:'1. Observer', home_step2:'2. Calculer', home_step3:'3. Comparer', home_step4:'4. Valider', home_data_status:'STATUT DES DONNÉES', home_poc:'Preuve de concept', home_formal_sites:'Sites formalisés', home_priority_candidates:'Sites à valider', home_illustrative:'Ensemble du catalogue', home_external_calibration:'Calibration externe', home_to_conduct:'À conduire', home_interpretation:'INTERPRÉTATION', home_signal_not_verdict:'Le BRₘ est un signal, pas un verdict', home_signal_text:'BRₘ⁰ est exploratoire. Un franchissement du seuil sert à prioriser l’analyse et ne remplace ni expertise locale, ni protocole statistique, ni validation indépendante.',
    pres_title:'Présentation de l’Observatoire', pres_p1:'L’Observatoire International GMA (Global Mesological Alert) est une plateforme dédiée à la détection et à la gestion des ruptures écologiques et institutionnelles. Il s’appuie sur le concept de Capital Vivant et sur l’écologie opérationnelle.', pres_p2:'Le Capital Vivant désigne l’ensemble des infrastructures critiques de subsistance — biodiversité, sols, eau et savoirs traditionnels associés — sans lesquelles la viabilité des territoires et la dignité de leurs habitants ne peuvent être assurées. L’Observatoire transforme cette intuition en un cadre de diagnostic mesurable.', pres_p3:'Le système d’alerte mésologique globale (GMA) propose un signal heuristique, l’indice de rupture mésologique (BRₘ), conçu pour prioriser l’investigation et structurer le jugement expert. La version actuelle (BRₘ⁰) est exploratoire. La version calibrée (BRₘ★) est l’objet du protocole Delphi n=20.', pres_p4:'L’Observatoire s’adresse aux chercheurs, gestionnaires de territoires et experts volontaires souhaitant contribuer à la validation empirique du cadre sur des sites prioritaires méditerranéens, nord-africains et internationaux.',
    book_title:'Ouvrage de référence', book_subtitle:'De l’expérience méditerranéenne à un cadre exploratoire de résilience territoriale', author_title:'L’auteur', author_bio:'Mourad Ahmim est Ph.D. en sciences biologiques, spécialiste des mammifères et des chauves-souris. Ses travaux portent sur l’écologie opérationnelle et la mésologie, les systèmes socio-écologiques méditerranéens et nord-africains, la résilience territoriale et la formalisation d’outils d’alerte (GMA, BRₘ, médiance de résilience).', contact_orcid:'ORCID', epistemic_title:'Statut épistémique', epistemic_text:'Ce travail présente un cadre théorique, un système d’indices et une preuve de concept empirique (n=10 sites algériens). Il ne constitue pas une validation externe. La calibration formelle (n=20, double notation en aveugle, poids fixés avant ROC) relève du protocole Delphi en cours.',
    formulas_title:'Formules et définitions', normalisation_kicker:'SECTION MÉTHODOLOGIQUE — INDICES',
    nav_indices:'Indices', indices_title:'Calculs complémentaires des indices', tau_calc_title:'Trajection τ(t) — calcul direct', tau_calc_intro:'Lorsque B, S, P et ρ sont disponibles, la trajection peut être calculée directement. Les valeurs préremplies reproduisent le cas de preuve de concept Djurdjura.', btn_tau:'Calculer τ(t)', bri_calc_title:'BRI dynamique — vitesse de changement', bri_calc_intro:'Deux observations distinctes de la trajection et une durée explicite sont nécessaires. Aucun BRI n’est inventé en l’absence de données temporelles.', btn_bri:'Calculer le BRI dynamique', et_calc_title:'Coefficient E(t) — substitution de l’eau', et_calc_intro:'Pour l’eau, E(t) rapporte les volumes importé, dessalé et réutilisé au volume consommé. Le résultat est borné à [0,1].', et_imported:'Volume importé', et_desal:'Volume dessalé', et_reused:'Volume réutilisé', et_consumed:'Volume consommé', btn_et:'Calculer E(t)', implementation_warning_title:'Important', implementation_warning:'Ces calculs appliquent les équations déclarées. Ils ne transforment pas des estimations en validation empirique. Les valeurs maîtresses de la preuve de concept restent celles de la Table A.0 jusqu’à leur re-calcul selon le protocole.',
    norm_bri:'BRI_dyn=(τ₂−τ₁)/(t₂−t₁). Deux observations distinctes et une durée explicite sont nécessaires ; aucune valeur n’est inventée quand elles manquent.', norm_adj:'BRₘ_adj=BRₘ×(1−E(t)). E(t)>0,70 signale, selon la convention actuelle, une stabilité fortement soutenue par substitution technologique.', norm_details_title:'Détails des fonctions de normalisation', norm_family1_title:'Famille 1 — Variables bornées', norm_family1:'x̂ = clip((x_ref−x_obs)/(x_ref−x_floor),0,1). Les références sont définies par domaine biogéographique.', norm_family2_title:'Famille 2 — Variables de ratio', norm_family2:'x̂ = min(1, ln(1+q/q_sust)/ln(1+k)), avec k=5. La saturation à ×5 correspond à l’ancrage « extrême » du protocole.', norm_aggregation_title:'Agrégation de ΔP', norm_aggregation:'ΔP=Σw_k x̂_k, avec Σw_k=1. Un indicateur manquant n’est pas imputé à zéro : les poids sont redistribués sur les indicateurs observés et la substitution est signalée.', norm_examples_title:'Exemples fonctionnels publiés', norm_examples:'Souf–M’Zab : 70→116 Hm³/an pour une recharge d’environ 25 Hm³/an donne q/q_sust≈4,6 et x̂≈0,96. Guerbes–Senhadja : NDVI 0,63→0,41 avec x_ref=0,72 et x_floor=0,12 donne x̂≈0,52.',
 f1_title:'1. Indice de Rupture Mésologique (BRₘ)', f1_desc:'Signal heuristique de déséquilibre entre pression anthropique et résilience écologique. Le seuil ≈ 1,20 est provisoire et ne constitue pas un seuil réglementaire.', f1_dp_text:'Pression anthropique relative normalisée [0,1]', f1_r_text:'Résilience écologique normalisée [0,1], avec R > 0 dans le calcul', f1_mu_text:'Poids de vulnérabilité, à calibrer par Delphi', f1_vi_text:'Intensité observée de la vulnérabilité [0,1]',
    f2_title:'2. BRₘ ajusté', f2_desc:'Le BRₘ ajusté tient compte de la substitution techno-institutionnelle : BRₘ_adj = BRₘ × (1 − E(t)).', f2_brm:'BRₘ — signal de rupture mésologique avant correction', f2_et:'E(t) — coefficient de substitution techno-institutionnelle [0,1]', f2_et_def:'Part de la stabilité territoriale reposant sur des apports technologiques ou institutionnels externes. Pour l’eau : (volume importé + dessalé + réutilisé) / volume consommé.', f2_rule:'E(t) > 0,70 indique une stabilité fortement soutenue par substitution technologique.',
    f3_title:'3. Trajection τ(t)', f3_desc:'La trajection modélise le degré de co-production vivante entre une communauté et son milieu.', f3_b:'B(t) — composante bio-écologique : intégrité écologique observée [0,1]', f3_s:'S(t) — composante socio-culturelle : vitalité des savoirs et pratiques de gestion [0,1]', f3_p:'P(t) — composante perceptive/existentielle : qualité vécue du milieu, attachement au lieu [0,1]', f3_rho:'ρ — paramètre de couplage : intensité de la co-production active entre communauté et milieu [0,1]', f3_op:'Φ — opérateur d’agrégation non substituable ; moyenne géométrique par défaut',
    f4_title:'4. Indice de Régénération Bioculturelle (BRI)', normalisation_title:'Paramétrage et normalisation des composantes', normalisation_intro:'Les indices GMA ne reçoivent pas directement des grandeurs physiques hétérogènes. Les variables brutes sont d’abord normalisées selon une règle déclarée, puis agrégées. Les 10 valeurs maîtresses publiées restent des scores de rubrique de preuve de concept.', normalisation_source:'Référence : Annexe A.2.2 et A.2.2 bis du protocole GMA.', norm_dp:'Pression anthropique : moyenne pondérée des sous-pressions normalisées. Variables de ratio : transformation logarithmique de l’excès q/q_sust, saturation avec k=5.', norm_e:'E(t) est, pour l’eau, la part de stabilité reposant sur des volumes importés, dessalés ou réutilisés rapportés au volume consommé.', norm_r:'Résilience écologique : score normalisé [0,1] construit sur un référentiel biogéographique explicite ; R doit rester >0 dans BRₘ.', norm_mu:'Poids des vulnérabilités : μᵢ≥0 et Σμᵢ=1 par site. Dans BRₘ⁰ ils sont issus d’un jugement expert ; BRₘ★ doit les fixer avant ROC.', norm_v:'Intensités de vulnérabilité [0,1] ; les ancres et leur cardinalisation doivent être documentées.', norm_tau:'τ(t)=ρ·(B·S·P)^(1/3), avec B, S, P et ρ normalisés ou bornés dans [0,1].', calc_published_title:'Charger une valeur publiée', calc_published_placeholder:'— Sélectionner un site formalisé —', calc_published_note:'Valeur de preuve de concept publiée.', f4_desc:'Le BRI dynamique suit la vitesse de changement du Capital Vivant entre deux temps d’observation.', f4_t1:'τ(t₁) — trajection au temps initial', f4_t2:'τ(t₂) — trajection au temps final', f4_time:'t₂ − t₁ — durée de la fenêtre d’observation', f4_read:'BRI > 0 indique une trajectoire de régénération ; BRI < 0 indique une dégradation. La magnitude doit être interprétée selon la fenêtre d’observation et le référentiel de normalisation.',
    map_title:'Carte des sites — Catalogue GMA', map_desc:'10 sites formalisés et 15 sites à valider. Les marqueurs sont colorés selon le phénotype ; le fond satellite est affiché en couleur.', filter_label:'Phénotype', filter_all:'Tous', filter_rupture:'Rupture', filter_resilience:'Résilience', filter_contre:'Contre-cas', filter_regen:'Régénération', search_placeholder:'Rechercher un site, pays ou biome…', status_all:'Tous les statuts', status_confirmed:'Formalisés', status_validate:'À VALIDER', status_filter:'Filtrer par statut', reset:'Réinitialiser',
    calc_title:'Calculateur BRₘ', calc_dp_label:'ΔP — Pression anthropique relative (0–1)', calc_r_label:'R — Résilience écologique (0–1)', calc_et_label:'E(t) — Substitution techno-institutionnelle (optionnel)', calc_vuln_title:'Vulnérabilités (μ × v)', btn_add_vuln:'+ Ajouter un facteur', btn_calc:'Calculer le BRₘ', method_reading_label:'Lecture :', method_reading:'BRₘ compare la pression relative à la résilience, puis applique l’amplification liée aux vulnérabilités. BRₘ_adj intègre E(t). Les valeurs doivent rester interprétables et documentées.', calc_result_title:'Résultat BRₘ', calc_state:'État', calc_raw:'BRₘ brut', calc_adjusted:'BRₘ ajusté', calc_amplification:'Amplification', calc_ratio:'ΔP / R', calc_use_adjusted:'L’état affiché utilise le BRₘ ajusté lorsque E(t) est renseigné.', state_security:'RÉSILIENCE', state_alert:'ZONE INTERMÉDIAIRE', state_rupture:'RUPTURE',
    delphi_title:'Appel à experts volontaires — Calibration n=20', delphi_intro:'Qui recherchons-nous ? Des experts volontaires en écologie, hydrogéologie, gouvernance, modélisation, géographie et anthropologie écologique pour participer à un protocole Delphi en 3 rounds et calibrer les poids μᵢ et la validation des sites.', delphi_commit:'La participation s’inscrit dans le protocole Delphi de calibration ; les modalités et le nombre de tours seront communiqués aux experts sélectionnés. La lecture préalable du protocole et de l’ouvrage est recommandée.', contact_label:'Contact', sites_title:'Catalogue des sites', sites_desc:'Le catalogue affiché ci-dessous rassemble les 25 sites présents dans la version actuelle : 10 sites formalisés et 15 sites à VALIDER. Aucun site n’est masqué derrière une sous-liste.', sites_formal:'A. Sites formalisés (10)', sites_cand:'B. Sites À VALIDER (15)', sites_note:'Le statut « À VALIDER » signifie que le site est proposé pour validation indépendante ; il ne signifie pas qu’un jugement définitif a déjà été porté.', apply_title:'Candidature volontaire', label_name:'Nom', label_email:'Email', label_expertise:'Domaine d’expertise', label_sites:'Sites d’intérêt (optionnel)', btn_apply:'Postuler comme expert volontaire',
    contact_title:'Contact', contact_contribution:'Préparer une contribution', contact_contribution_text:'Utilisez l’appel Delphi pour proposer une expertise ou un site à valider. Le formulaire prépare un email structuré à partir des informations saisies.', contact_go_delphi:'Aller au formulaire Delphi', contact_email:'Email', contact_doi:'DOI', license:'Licence CC BY-NC-SA 4.0 — Non commercialisable', footer_copy:'© 2026 Observatoire International GMA — Capital Vivant · Mourad Ahmim',
    map_formal:'Formalisés', map_candidates:'À VALIDER', map_total:'Total catalogue', map_scored:'BRₘ renseignés', table_filtered:'Catalogue filtré', site:'Site', country:'Pays', phenotype:'Phénotype', status:'Statut', brm:'BRₘ', map_btn:'Carte', site_sheet_map:'Voir sur la carte', site_sheet_unscored:'BRₘ — non scoré', popup_file:'Fiche du site', not_scored:'BRₘ non scoré', status_security:'Résilience', status_alert:'Zone intermédiaire', status_rupture:'Rupture', brm_nonscored:'Non scoré', brm_zone:'Zone intermédiaire', interpretation:'Interprétation', threshold:'seuil heuristique provisoire ≈ 1,20', calc_error_main:'ΔP et R doivent rester dans [0,1] avec R > 0 ; E(t) doit rester dans [0,1].', calc_error_vuln:'Les μᵢ et vᵢ doivent rester dans [0,1].', communication_ready:'Votre logiciel de messagerie va être préparé avec les informations saisies.', add_factor:'Facteur', remove:'Supprimer', vuln_label:'Vulnérabilité'
  },
  en: {
    brand:'GMA — Living Capital Observatory', nav_home:'Home', nav_pres:'Presentation', nav_formulas:'Formulas', nav_map:'GIS Map', nav_calc:'BRₘ Calculator', nav_delphi:'Delphi', nav_contact:'Contact',
    hero_title_top:'International GMA Observatory', hero_title_bottom:'Living Capital', hero_kicker:'GLOBAL MESOLOGY ALERT', hero_sub:'LIVING CAPITAL · MONITORING · ANALYSIS · PROTECTION',
    cta_calc:'Calculate BRₘ →', cta_delphi:'Contribute as a volunteer', cta_map:'Site monitoring', stat1:'Formalised sites', stat2:'Sites to validate', stat3:'BRₘ max (El Bayadh–Djelfa)', stat4:'Heuristic threshold',
    home_kicker:'GMA · quick read', home_operational:'OPERATIONAL FRAMEWORK', home_concept:'From concept to territorial signal', home_concept_text:'The site does not only present BRₘ: it shows how to move from pressure and resilience to an investigation decision and then to expert validation.', home_step1:'1. Observe', home_step2:'2. Calculate', home_step3:'3. Compare', home_step4:'4. Validate', home_data_status:'DATA STATUS', home_poc:'Proof of concept', home_formal_sites:'Formalised sites', home_priority_candidates:'Sites to validate', home_illustrative:'Full catalogue', home_external_calibration:'External calibration', home_to_conduct:'To be conducted', home_interpretation:'INTERPRETATION', home_signal_not_verdict:'BRₘ is a signal, not a verdict', home_signal_text:'BRₘ⁰ is exploratory. Crossing the threshold helps prioritise analysis and does not replace local expertise, a statistical protocol or independent validation.',
    pres_title:'Observatory Presentation', pres_p1:'The International GMA Observatory (Global Mesological Alert) is a platform dedicated to detecting and managing ecological and institutional ruptures. It builds on the Living Capital concept and operational ecology.', pres_p2:'Living Capital refers to critical subsistence infrastructures — biodiversity, soils, water and associated traditional knowledge — without which territorial viability and human dignity can be ensured only imperfectly. The Observatory turns this intuition into a measurable diagnostic framework.', pres_p3:'The Global Mesological Alert system (GMA) proposes a heuristic signal, the Mesological Rupture Index (BRₘ), designed to prioritise investigation and structure expert judgement. The current version (BRₘ⁰) is exploratory. The calibrated version (BRₘ★) is the object of the n=20 Delphi protocol.', pres_p4:'The Observatory is intended for researchers, territorial managers and volunteer experts wishing to contribute to empirical validation across priority Mediterranean, North African and international sites.',
    book_title:'Reference book', book_subtitle:'From Mediterranean lessons to an exploratory framework for territorial resilience', author_title:'The author', author_bio:'Mourad Ahmim holds a Ph.D. in Biological Sciences and is a specialist in mammals and bats. His work focuses on operational ecology and mesology, Mediterranean and North African socio-ecological systems, territorial resilience, and formalising alert tools (GMA, BRₘ, resilience mediance).', contact_orcid:'ORCID', epistemic_title:'Epistemic status', epistemic_text:'This work presents a theoretical framework, an index system and an empirical proof of concept (n=10 Algerian sites). It is not an external validation. Formal calibration (n=20, blind double scoring, weights fixed before ROC) is part of the ongoing Delphi protocol.',
    formulas_title:'Formulas and definitions', normalisation_kicker:'METHODOLOGICAL SECTION — INDICES',
    nav_indices:'Indices', indices_title:'Complementary index calculations', tau_calc_title:'Trajection τ(t) — direct calculation', tau_calc_intro:'When B, S, P and ρ are available, trajection can be calculated directly. The prefilled values reproduce the Djurdjura proof-of-concept case.', btn_tau:'Calculate τ(t)', bri_calc_title:'Dynamic BRI — rate of change', bri_calc_intro:'Two distinct trajection observations and an explicit time interval are required. No BRI value is fabricated when temporal data are missing.', btn_bri:'Calculate dynamic BRI', et_calc_title:'E(t) coefficient — water substitution', et_calc_intro:'For water, E(t) relates imported, desalinated and reused volumes to total consumed volume. The result is bounded to [0,1].', et_imported:'Imported volume', et_desal:'Desalinated volume', et_reused:'Reused volume', et_consumed:'Consumed volume', btn_et:'Calculate E(t)', implementation_warning_title:'Important', implementation_warning:'These calculators apply the declared equations. They do not turn estimates into empirical validation. The proof-of-concept master values remain those of Table A.0 until they are re-derived under the stated protocol.',
    norm_bri:'BRI_dyn=(τ₂−τ₁)/(t₂−t₁). Two distinct observations and an explicit duration are required; no value is fabricated when they are missing.', norm_adj:'BRₘ_adj=BRₘ×(1−E(t)). E(t)>0.70 indicates, under the current convention, stability strongly supported by technological substitution.', norm_details_title:'Details of the normalisation functions', norm_family1_title:'Family 1 — Bounded variables', norm_family1:'x̂ = clip((x_ref−x_obs)/(x_ref−x_floor),0,1). Reference values are declared by biogeographical domain.', norm_family2_title:'Family 2 — Ratio-scale variables', norm_family2:'x̂ = min(1, ln(1+q/q_sust)/ln(1+k)), with k=5. Saturation at ×5 corresponds to the protocol’s “extreme” anchor.', norm_aggregation_title:'Aggregation of ΔP', norm_aggregation:'ΔP=Σw_k x̂_k, with Σw_k=1. A missing indicator is not imputed as zero: weights are redistributed across observed indicators and the substitution is reported.', norm_examples_title:'Published functional examples', norm_examples:'Souf–M’Zab: 70→116 Hm³/year against roughly 25 Hm³/year recharge gives q/q_sust≈4.6 and x̂≈0.96. Guerbes–Senhadja: NDVI 0.63→0.41 with x_ref=0.72 and x_floor=0.12 gives x̂≈0.52.',
 f1_title:'1. Mesological Rupture Index (BRₘ)', f1_desc:'Heuristic signal of imbalance between anthropogenic pressure and ecological resilience. The ≈ 1.20 threshold is provisional and is not a regulatory threshold.', f1_dp_text:'Normalised relative anthropogenic pressure [0,1]', f1_r_text:'Normalised ecological resilience [0,1], with R > 0 in the calculation', f1_mu_text:'Vulnerability weight, to be calibrated through Delphi', f1_vi_text:'Observed vulnerability intensity [0,1]',
    f2_title:'2. Adjusted BRₘ', f2_desc:'The adjusted BRₘ accounts for techno-institutional substitution: BRₘ_adj = BRₘ × (1 − E(t)).', f2_brm:'BRₘ — mesological rupture signal before correction', f2_et:'E(t) — techno-institutional substitution coefficient [0,1]', f2_et_def:'Share of territorial stability relying on external technological or institutional inputs. For water: (imported + desalinated + reused volume) / consumed volume.', f2_rule:'E(t) > 0.70 indicates stability strongly supported by technological substitution.',
    f3_title:'3. Trajection τ(t)', f3_desc:'Trajection models the degree of living co-production between a community and its milieu.', f3_b:'B(t) — bio-ecological component: observed ecological integrity [0,1]', f3_s:'S(t) — socio-cultural component: vitality of knowledge and management practices [0,1]', f3_p:'P(t) — perceptual/existential component: lived quality of the milieu and sense of place [0,1]', f3_rho:'ρ — coupling parameter: intensity of active co-production between community and milieu [0,1]', f3_op:'Φ — non-substitutable aggregation operator; geometric mean by default',
    f4_title:'4. Biocultural Regeneration Index (BRI)', normalisation_title:'Component parameterisation and normalisation', normalisation_intro:'GMA indices do not directly combine heterogeneous physical quantities. Raw variables are first normalised under a declared rule and then aggregated. The 10 published master values remain rubric-based proof-of-concept scores.', normalisation_source:'Reference: GMA Protocol Appendix A.2.2 and A.2.2 bis.', norm_dp:'Anthropogenic pressure: weighted mean of normalised sub-pressures. Ratio-scale variables use a logarithmic exceedance transform with k=5.', norm_e:'For water, E(t) is the share of stability resting on imported, desalinated or reused volumes relative to total consumed volume.', norm_r:'Ecological resilience: normalised score [0,1] built against an explicit biogeographical reference; R must remain >0 in BRₘ.', norm_mu:'Vulnerability weights: μᵢ≥0 and Σμᵢ=1 per site. In BRₘ⁰ they are expert judgements; BRₘ★ must fix them before ROC.', norm_v:'Vulnerability intensities [0,1]; anchors and cardinalisation must be documented.', norm_tau:'τ(t)=ρ·(B·S·P)^(1/3), with B, S, P and ρ bounded in [0,1].', calc_published_title:'Load a published value', calc_published_placeholder:'— Select a formalised site —', calc_published_note:'Published proof-of-concept value.', f4_desc:'Dynamic BRI tracks the rate of change in Living Capital between two observation times.', f4_t1:'τ(t₁) — trajection at the initial time', f4_t2:'τ(t₂) — trajection at the final time', f4_time:'t₂ − t₁ — duration of the observation window', f4_read:'BRI > 0 indicates a regeneration trajectory; BRI < 0 indicates degradation. Magnitude must be interpreted relative to the observation window and the normalisation baseline.',
    map_title:'Site map — GMA catalogue', map_desc:'10 formalised sites and 15 sites to validate. Markers are coloured by phenotype; the satellite basemap is displayed in colour.', filter_label:'Phenotype', filter_all:'All', filter_rupture:'Rupture', filter_resilience:'Resilience', filter_contre:'Counter-case', filter_regen:'Regeneration', search_placeholder:'Search site, country or biome…', status_all:'All statuses', status_confirmed:'Formalised', status_validate:'TO VALIDATE', status_filter:'Filter by status', reset:'Reset',
    calc_title:'BRₘ Calculator', calc_dp_label:'ΔP — Relative anthropogenic pressure (0–1)', calc_r_label:'R — Ecological resilience (0–1)', calc_et_label:'E(t) — Techno-institutional substitution (optional)', calc_vuln_title:'Vulnerabilities (μ × v)', btn_add_vuln:'+ Add factor', btn_calc:'Calculate BRₘ', method_reading_label:'Reading:', method_reading:'BRₘ compares relative pressure with resilience, then applies vulnerability amplification. BRₘ_adj integrates E(t). Values must remain interpretable and documented.', calc_result_title:'BRₘ result', calc_state:'State', calc_raw:'Raw BRₘ', calc_adjusted:'Adjusted BRₘ', calc_amplification:'Amplification', calc_ratio:'ΔP / R', calc_use_adjusted:'The displayed state uses adjusted BRₘ when E(t) is provided.', state_security:'RESILIENCE', state_alert:'INTERMEDIATE ZONE', state_rupture:'RUPTURE',
    delphi_title:'Call for volunteer experts — Calibration n=20', delphi_intro:'Who are we looking for? Volunteer experts in ecology, hydrogeology, governance, modelling, geography and ecological anthropology for a 3-round Delphi protocol to calibrate μᵢ weights and validate sites.', delphi_commit:'Participation follows the GMA Delphi calibration protocol; the format and number of rounds will be communicated to selected experts. Prior reading of the protocol and the book is recommended.', contact_label:'Contact', sites_title:'Site catalogue', sites_desc:'The catalogue below contains all 25 sites in the current version: 10 formalised sites and 15 sites TO VALIDATE. No site is hidden behind a secondary list.', sites_formal:'A. Formalised sites (10)', sites_cand:'B. Sites TO VALIDATE (15)', sites_note:'“TO VALIDATE” means the site is proposed for independent validation; it does not mean that a definitive judgement has already been established.', apply_title:'Volunteer application', label_name:'Name', label_email:'Email', label_expertise:'Field of expertise', label_sites:'Sites of interest (optional)', btn_apply:'Apply as volunteer expert',
    contact_title:'Contact', contact_contribution:'Prepare a contribution', contact_contribution_text:'Use the Delphi call to propose expertise or a site for validation. The form prepares a structured email from the information entered.', contact_go_delphi:'Open Delphi form', contact_email:'Email', contact_doi:'DOI', license:'CC BY-NC-SA 4.0 licence — Non-commercial', footer_copy:'© 2026 International GMA Observatory — Living Capital · Mourad Ahmim',
    map_formal:'Formalised', map_candidates:'TO VALIDATE', map_total:'Total catalogue', map_scored:'BRₘ reported', table_filtered:'Filtered catalogue', site:'Site', country:'Country', phenotype:'Phenotype', status:'Status', brm:'BRₘ', map_btn:'Map', site_sheet_map:'View on map', site_sheet_unscored:'BRₘ — not scored', popup_file:'Site sheet', not_scored:'BRₘ not scored', status_security:'Resilience', status_alert:'Intermediate zone', status_rupture:'Rupture', brm_nonscored:'Not scored', brm_zone:'Intermediate zone', interpretation:'Interpretation', threshold:'provisional heuristic threshold ≈ 1.20', calc_error_main:'ΔP and R must remain in [0,1] with R > 0; E(t) must remain in [0,1].', calc_error_vuln:'μᵢ and vᵢ must remain in [0,1].', communication_ready:'Your email client will be prepared with the entered information.', add_factor:'Factor', remove:'Remove', vuln_label:'Vulnerability'
  }
};

const countryI18n = {
  'Algérie': {fr:'Algérie',en:'Algeria'}, 'Espagne':{fr:'Espagne',en:'Spain'}, 'Turquie':{fr:'Turquie',en:'Türkiye'}, 'USA':{fr:'États-Unis',en:'USA'}, 'Australie':{fr:'Australie',en:'Australia'}, 'Chili':{fr:'Chili',en:'Chile'}, 'Jordanie':{fr:'Jordanie',en:'Jordan'}, 'Niger':{fr:'Niger',en:'Niger'}, 'Botswana':{fr:'Botswana',en:'Botswana'}, 'Chine':{fr:'Chine',en:'China'}, 'France':{fr:'France',en:'France'}, 'Kazakhstan/Ouzbékistan':{fr:'Kazakhstan/Ouzbékistan',en:'Kazakhstan/Uzbekistan'}
};
const biomeI18n = {
  'Méditerranéen montagnard':{fr:'Méditerranéen montagnard',en:'Mountain Mediterranean'}, 'Steppe':{fr:'Steppe',en:'Steppe'}, 'Oasis saharienne':{fr:'Oasis saharienne',en:'Saharan oasis'}, 'Zone humide Ramsar':{fr:'Zone humide Ramsar',en:'Ramsar wetland'}, 'Forêt périurbaine':{fr:'Forêt périurbaine',en:'Peri-urban forest'}, 'Parc National':{fr:'Parc national',en:'National park'}, 'Saharien montagnard':{fr:'Saharien montagnard',en:'Mountain Sahara'}, 'Forêt de chênes':{fr:'Forêt de chênes',en:'Oak forest'}, 'Sahara':{fr:'Sahara',en:'Sahara'}, 'Méditerranéen semi-aride':{fr:'Méditerranéen semi-aride',en:'Semi-arid Mediterranean'}, 'Méditerranéen':{fr:'Méditerranéen',en:'Mediterranean'}, 'Chaparral':{fr:'Chaparral',en:'Chaparral'}, 'Bassin fluvial':{fr:'Bassin fluvial',en:'River basin'}, 'Désert':{fr:'Désert',en:'Desert'}, 'Aride':{fr:'Aride',en:'Arid'}, 'Sahélien':{fr:'Sahélien',en:'Sahelian'}, 'Delta intérieur':{fr:'Delta intérieur',en:'Inland delta'}, 'Hauts plateaux':{fr:'Hauts plateaux',en:'High plateau'}, 'Loess':{fr:'Loess',en:'Loess'}, 'Périurbain':{fr:'Périurbain',en:'Peri-urban'}, 'Lagune méditerranéenne':{fr:'Lagune méditerranéenne',en:'Mediterranean lagoon'}, 'Réserve de biosphère':{fr:'Réserve de biosphère',en:'Biosphere reserve'}, 'Lac endoréique':{fr:'Lac endoréique',en:'Endorheic lake'}, 'Récif corallien':{fr:'Récif corallien',en:'Coral reef'}
};

function t(k){return i18n[currentLang]?.[k] ?? i18n.fr[k] ?? k;}
function setLang(lang){
  currentLang=lang; localStorage.setItem('gmaLang',lang); document.documentElement.lang=lang; document.title=lang==='en'?'International GMA Observatory — Living Capital':'Observatoire International GMA — Capital vivant';
  document.querySelectorAll('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));
  document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(i18n[lang]?.[k]!==undefined)el.textContent=i18n[lang][k];});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));
  document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria))); document.querySelectorAll('[data-vuln-fr]').forEach(el=>{const v=el.dataset['vuln'+(lang==='en'?'En':'Fr')]; if(v) el.value=v;});
  if(window.renderMathInElement) renderMathInElement(document.body,{delimiters:[{left:'\\[',right:'\\]',display:true},{left:'\\(',right:'\\)',display:false}]});
  renderSiteCatalog(); renderSiteTable(); renderHeroStats();
  if(mapInstance){
    mapInstance.markers.forEach(({m,s})=>m.setPopupContent(sitePopup(s)));
    renderMapStats(document.getElementById('map-stats'));
  }
  if(document.getElementById('calc-result')?.dataset.hasResult==='1') reRenderCalcResult();
}
function showPage(id){
  document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));
  const page=document.getElementById(id); if(page) page.classList.add('active');
  document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));
  if(id==='carte'&&typeof L!=='undefined') setTimeout(()=>{if(!mapInstance)mapInstance=initMap('map');else mapInstance.map.invalidateSize();applySiteFilters();},150);
  if(id==='delphi')renderSiteCatalog();
  window.scrollTo({top:0,behavior:'smooth'});
}
function siteColor(ph){return ({'Rupture':'#c2413d','Résilience':'#2f855a','Contre-cas':'#b7791f','Régénération':'#3569a8'})[ph]||'#64748b';}
function phenotypeClass(ph){return ({'Rupture':'rupture','Résilience':'resilience','Contre-cas':'counter','Régénération':'regeneration'})[ph]||'neutral';}
function translatePhenotype(p){return ({'Rupture':t('filter_rupture'),'Résilience':t('filter_resilience'),'Contre-cas':t('filter_contre'),'Régénération':t('filter_regen')})[p]||p;}
function translateStatus(s){return s==='confirmé'?t('status_confirmed'):s==='à valider'?t('status_validate'):s;}
function transCountry(s){return countryI18n[s]?.[currentLang]||s;}
function transBiome(s){return biomeI18n[s]?.[currentLang]||s;}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function filteredSites(){const q=siteSearch.trim().toLowerCase();return GMA_SITES.filter(s=>{const pOk=activePhenotype==='all'||s.phenotype===activePhenotype;const stOk=siteStatus==='all'||s.status===siteStatus;const text=(s.name+' '+transCountry(s.country)+' '+transBiome(s.biome||'')).toLowerCase();return pOk&&stOk&&(!q||text.includes(q));});}
function sitePopup(s){return `<div class="map-popup"><strong>${escapeHtml(s.name)}</strong><br>${escapeHtml(transCountry(s.country))}<br><span class="popup-phenotype"><b style="background:${siteColor(s.phenotype)}"></b>${escapeHtml(translatePhenotype(s.phenotype))}</span><br><span class="popup-status">${escapeHtml(translateStatus(s.status))}</span><br><small>${escapeHtml(transBiome(s.biome||''))}</small><br><strong>${s.brM==null?t('not_scored'):t('brm')+' '+s.brM.toFixed(2)}</strong><br><button type="button" onclick="showSiteInfo(${s.id})">${t('popup_file')}</button></div>`;}
function renderSiteCatalog(){
  const formal=GMA_SITES.filter(s=>s.status==='confirmé'), validate=GMA_SITES.filter(s=>s.status==='à valider');
  const render=arr=>arr.map(s=>`<article class="site-sheet site-card"><div class="site-top"><h4>${escapeHtml(s.name)}</h4><span class="phenotype-pill ${phenotypeClass(s.phenotype)}">${escapeHtml(translatePhenotype(s.phenotype))}</span></div><div class="site-meta"><span>${escapeHtml(transCountry(s.country))}</span><span>${escapeHtml(transBiome(s.biome||''))}</span></div><div class="site-status-line"><span class="site-status ${s.status==='à valider'?'validate':'formal'}">${escapeHtml(translateStatus(s.status))}</span>${s.brM==null?`<span class="small-note">${t('not_scored')}</span>`:`<strong>${t('brm')} ${s.brM.toFixed(2)}</strong>`}</div><div class="site-bottom"><button type="button" class="text-button" onclick="focusSite(${s.id})">${t('site_sheet_map')}</button></div></article>`).join('');
  const a=document.getElementById('formal-sites'),b=document.getElementById('candidate-sites'); if(a)a.innerHTML=render(formal); if(b)b.innerHTML=render(validate);
  const count=document.getElementById('site-catalog-count'); if(count)count.textContent=`${GMA_SITES.length}`;
}
function renderHeroStats(){const max=GMA_SITES.filter(s=>Number.isFinite(s.brM)).reduce((m,s)=>Math.max(m,s.brM),0);const el=document.getElementById('hero-max-brm');if(el)el.textContent=max.toFixed(2);}
function initMap(containerId){
  const el=document.getElementById(containerId); if(!el||typeof L==='undefined')return null;
  const map=L.map(containerId,{zoomControl:true}).setView([28,10],3);
  const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'&copy; Esri, Maxar, Earthstar Geographics',maxZoom:19});
  const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19});
  satellite.addTo(map);
  L.control.layers({'Satellite — couleur':satellite,'Plan — OSM':street},null,{collapsed:false,position:'topright'}).addTo(map);
  const markers=[];
  GMA_SITES.forEach(s=>{if(s.lat==null||s.lng==null)return;const m=L.circleMarker([s.lat,s.lng],{radius:s.status==='confirmé'?8:7,fillColor:siteColor(s.phenotype),color:'#ffffff',weight:2,fillOpacity:.95}).addTo(map);m.bindPopup(sitePopup(s));markers.push({m,s});});
  if(markers.length)map.fitBounds(L.featureGroup(markers.map(x=>x.m)).getBounds().pad(.12));
  renderMapStats(document.getElementById('map-stats'));
  return {map,markers};
}
function renderMapStats(el){if(!el)return;const formal=GMA_SITES.filter(s=>s.status==='confirmé').length,validate=GMA_SITES.filter(s=>s.status==='à valider').length,scored=GMA_SITES.filter(s=>s.brM!=null).length;el.innerHTML=`<div class="stat-box"><div class="n">${formal}</div><div class="l">${t('map_formal')}</div></div><div class="stat-box"><div class="n">${validate}</div><div class="l">${t('map_candidates')}</div></div><div class="stat-box"><div class="n">${GMA_SITES.length}</div><div class="l">${t('map_total')}</div></div><div class="stat-box"><div class="n">${scored}</div><div class="l">${t('map_scored')}</div></div>`;}
function applySiteFilters(){if(!mapInstance)return;const shown=new Set(filteredSites().map(s=>s.id));mapInstance.markers.forEach(({m,s})=>{if(shown.has(s.id)){if(!mapInstance.map.hasLayer(m))m.addTo(mapInstance.map);}else if(mapInstance.map.hasLayer(m))mapInstance.map.removeLayer(m);});renderSiteTable();}
function filterMap(phenotype){activePhenotype=phenotype;document.querySelectorAll('.filter-bar button[data-phenotype]').forEach(b=>b.classList.toggle('active',b.dataset.phenotype===phenotype));applySiteFilters();}
function resetSiteFilters(){siteSearch='';siteStatus='all';activePhenotype='all';const q=document.getElementById('site-search'),s=document.getElementById('site-status-filter');if(q)q.value='';if(s)s.value='all';filterMap('all');}
function renderSiteTable(){const el=document.getElementById('site-table');if(!el)return;const arr=filteredSites();el.innerHTML=`<div class="table-head"><strong>${t('table_filtered')}</strong><span>${arr.length}</span></div><div class="site-table"><table><thead><tr><th>${t('site')}</th><th>${t('country')}</th><th>${t('phenotype')}</th><th>${t('status')}</th><th>${t('brm')}</th><th></th></tr></thead><tbody>${arr.map(s=>`<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(transCountry(s.country))}</td><td><span class="dot" style="background:${siteColor(s.phenotype)}"></span>${escapeHtml(translatePhenotype(s.phenotype))}</td><td><span class="status-table ${s.status==='à valider'?'validate':'formal'}">${escapeHtml(translateStatus(s.status))}</span></td><td>${s.brM==null?'—':s.brM.toFixed(2)}</td><td><button type="button" class="text-button" onclick="focusSite(${s.id})">${t('map_btn')}</button></td></tr>`).join('')}</tbody></table></div>`;}
function focusSite(id){if(mapInstance){showPage('carte');const item=mapInstance.markers.find(x=>x.s.id===id);if(item){mapInstance.map.setView([item.s.lat,item.s.lng],6);item.m.openPopup();}}else{showPage('carte');setTimeout(()=>focusSite(id),300);}}
function showSiteInfo(id){const s=GMA_SITES.find(x=>x.id===id);if(!s)return;const msg=`${s.name}\n${transCountry(s.country)}\n${translatePhenotype(s.phenotype)}\n${translateStatus(s.status)}\n${t('brm')} : ${s.brM==null?t('not_scored'):s.brM.toFixed(2)}\n${transBiome(s.biome||'')}`;window.alert(msg);}

document.addEventListener('input',e=>{if(e.target.id==='site-search'){siteSearch=e.target.value;applySiteFilters();}});
document.addEventListener('change',e=>{if(e.target.id==='site-status-filter'){siteStatus=e.target.value;applySiteFilters();}});

function statusForBR(br){if(br<0.8)return {key:'state_security',cls:'resilience'};if(br<1.2)return {key:'state_alert',cls:'counter'};return {key:'state_rupture',cls:'rupture'};}
function populatePublishedSites(){const el=document.getElementById('published-site');if(!el)return;const sites=GMA_SITES.filter(s=>s.status==='confirmé'&&Number.isFinite(s.deltaP)&&Number.isFinite(s.rEco)&&Number.isFinite(s.vulnSum));el.innerHTML=`<option value="" data-i18n="calc_published_placeholder">${t('calc_published_placeholder')}</option>`+sites.map(s=>`<option value="${s.id}">${escapeHtml(s.name)} — ΔP ${s.deltaP.toFixed(2)} / R ${s.rEco.toFixed(2)} / Σμv ${s.vulnSum.toFixed(3)}</option>`).join('');translatePage();}
function loadPublishedSite(id){const s=GMA_SITES.find(x=>x.id===Number(id));if(!s)return;document.getElementById('deltaP').value=s.deltaP;document.getElementById('rEco').value=s.rEco;document.getElementById('eT').value=Number.isFinite(s.eT)?s.eT:0;const rows=[...document.querySelectorAll('#vuln-container .vuln-row')];if(rows[0]){rows[0].querySelector('.mu').value='1.00';rows[0].querySelector('.vi').value=s.vulnSum.toFixed(3);}rows.slice(1).forEach(r=>r.remove());const note=document.getElementById('published-site-note');if(note)note.textContent=`${s.source||t('calc_published_note')} — BRₘ publié ${Number.isFinite(s.brM)?s.brM.toFixed(2):'—'}.`;}
function calcBRm(e){
  e.preventDefault();
  const dP=parseFloat(document.getElementById('deltaP').value),R=parseFloat(document.getElementById('rEco').value),eT=parseFloat(document.getElementById('eT').value||0);
  if(!Number.isFinite(dP)||dP<0||dP>1||!Number.isFinite(R)||R<=0||R>1||!Number.isFinite(eT)||eT<0||eT>1)return showCalcError(t('calc_error_main'));
  let sum=0,invalid=false;document.querySelectorAll('.vuln-row').forEach(row=>{const mu=parseFloat(row.querySelector('.mu')?.value),vi=parseFloat(row.querySelector('.vi')?.value);if(!Number.isFinite(mu)||!Number.isFinite(vi)||mu<0||mu>1||vi<0||vi>1)invalid=true;sum+=(Number.isFinite(mu)?mu:0)*(Number.isFinite(vi)?vi:0);});
  if(invalid)return showCalcError(t('calc_error_vuln'));
  const amp=1+sum,ratio=dP/R,brM=ratio*amp,brMAdj=brM*(1-eT);const box=document.getElementById('calc-result');
  box.dataset.hasResult='1';box.dataset.brM=brM;box.dataset.brMAdj=brMAdj;box.dataset.amp=amp;box.dataset.ratio=ratio;box.style.display='block';
  renderCalcResult({brM,brMAdj,amp,ratio});box.scrollIntoView({behavior:'smooth',block:'nearest'});
}
function renderCalcResult(v){const box=document.getElementById('calc-result');const state=statusForBR(v.brMAdj);box.innerHTML=`<div class="calc-result-header"><div><div class="eyebrow">${t('calc_result_title')}</div><div class="calc-big">BRₘ ${v.brMAdj.toFixed(3)}</div></div><span class="phenotype-pill result-pill ${state.cls}">${t(state.key)}</span></div><div class="result-grid"><div class="result-item"><div class="lab">${t('calc_raw')}</div><div class="val">${v.brM.toFixed(3)}</div></div><div class="result-item"><div class="lab">${t('calc_adjusted')}</div><div class="val">${v.brMAdj.toFixed(3)}</div></div><div class="result-item"><div class="lab">${t('calc_amplification')}</div><div class="val">${v.amp.toFixed(3)}</div></div><div class="result-item"><div class="lab">${t('calc_ratio')}</div><div class="val">${v.ratio.toFixed(3)}</div></div></div><p class="calc-equation">BRₘ = (ΔP / R) × (1 + Σ μᵢvᵢ) → ${v.brM.toFixed(3)} ; BRₘ_adj = BRₘ × (1 − E(t)) → ${v.brMAdj.toFixed(3)}</p><p class="small-note"><strong>${t('calc_state')} :</strong> ${t(state.key)} · ${t('calc_use_adjusted')}</p>`;}
function reRenderCalcResult(){const box=document.getElementById('calc-result');if(box?.dataset.hasResult==='1')renderCalcResult({brM:parseFloat(box.dataset.brM),brMAdj:parseFloat(box.dataset.brMAdj),amp:parseFloat(box.dataset.amp),ratio:parseFloat(box.dataset.ratio)});}
function showCalcError(msg){const box=document.getElementById('calc-result');box.dataset.hasResult='0';box.style.display='block';box.innerHTML=`<div class="validation-error">${escapeHtml(msg)}</div>`;}
function addVuln(){const c=document.getElementById('vuln-container'),row=document.createElement('div');row.className='vuln-row';row.innerHTML=`<input type="text" value="${t('add_factor')}"><input type="number" class="mu" step="0.01" min="0" max="1" value="0.20"><input type="number" class="vi" step="0.01" min="0" max="1" value="0.50"><button type="button" class="remove-vuln" aria-label="${t('remove')}" onclick="this.parentElement.remove()">✕</button>`;c.appendChild(row);}
function showIndexResult(id,html){const el=document.getElementById(id);if(el){el.innerHTML=html;el.classList.add('visible');}}
function valid01(v){return Number.isFinite(v)&&v>=0&&v<=1;}
function calcTau(){const B=parseFloat(document.getElementById('tau-b').value),S=parseFloat(document.getElementById('tau-s').value),P=parseFloat(document.getElementById('tau-p').value),rho=parseFloat(document.getElementById('tau-rho').value);if(![B,S,P,rho].every(valid01))return showIndexResult('tau-result',`<div class="validation-error">${escapeHtml(t('calc_error_main'))}</div>`);const tau=rho*Math.cbrt(B*S*P);showIndexResult('tau-result',`<div class="index-result-value"><strong>τ(t) = ${tau.toFixed(4)}</strong><span>${currentLang==='fr'?'Calcul : ρ·(B·S·P)^(1/3)':'Calculation: ρ·(B·S·P)^(1/3)'}</span></div>`);}
function calcBRI(){const t1=parseFloat(document.getElementById('bri-t1').value),t2=parseFloat(document.getElementById('bri-t2').value),dt=parseFloat(document.getElementById('bri-dt').value);if(!valid01(t1)||!valid01(t2)||!Number.isFinite(dt)||dt<=0)return showIndexResult('bri-result',`<div class="validation-error">${escapeHtml(currentLang==='fr'?'τ(t₁), τ(t₂) doivent être dans [0,1] et t₂−t₁ doit être >0.':'τ(t₁), τ(t₂) must be within [0,1] and t₂−t₁ must be >0.')}</div>`);const bri=(t2-t1)/dt;const label=bri>0?(currentLang==='fr'?'RÉGÉNÉRATION':'REGENERATION'):bri<0?(currentLang==='fr'?'DÉGRADATION':'DEGRADATION'):(currentLang==='fr'?'STABLE':'STABLE');const cls=bri>0?'resilience':bri<0?'rupture':'counter';showIndexResult('bri-result',`<div class="index-result-value"><strong>BRI_dyn = ${bri.toFixed(4)}</strong><span class="phenotype-pill ${cls}">${label}</span></div>`);}
function calcEt(){const a=parseFloat(document.getElementById('et-imported').value)||0,b=parseFloat(document.getElementById('et-desal').value)||0,c=parseFloat(document.getElementById('et-reused').value)||0,d=parseFloat(document.getElementById('et-consumed').value);if([a,b,c,d].some(v=>!Number.isFinite(v)||v<0)||d<=0)return showIndexResult('et-result',`<div class="validation-error">${escapeHtml(currentLang==='fr'?'Les volumes doivent être ≥0 et le volume consommé >0.':'Volumes must be ≥0 and consumed volume must be >0.')}</div>`);const et=(a+b+c)/d;if(et>1)return showIndexResult('et-result',`<div class="validation-error">${escapeHtml(currentLang==='fr'?'E(t) dépasserait 1 : les volumes de substitution dépassent le volume consommé.':'E(t) would exceed 1: substitution volumes exceed total consumed volume.')}</div>`);const label=et>0.7?(currentLang==='fr'?'STABILITÉ FORTEMENT SOUTENUE PAR SUBSTITUTION':'STABILITY STRONGLY SUPPORTED BY SUBSTITUTION'):(currentLang==='fr'?'SUBSTITUTION ≤ 0,70':'SUBSTITUTION ≤ 0.70');const cls=et>0.7?'counter':'resilience';showIndexResult('et-result',`<div class="index-result-value"><strong>E(t) = ${et.toFixed(4)}</strong><span class="phenotype-pill ${cls}">${label}</span></div>`);}
function submitDelphi(e){e.preventDefault();const name=document.getElementById('delphi-name').value.trim(),email=document.getElementById('delphi-email').value.trim(),expertise=document.getElementById('delphi-expertise').value.trim(),sites=document.getElementById('delphi-sites').value.trim();const en=currentLang==='en';const subject=encodeURIComponent(`${en?'GMA Delphi application':'Candidature Delphi GMA'} — ${name}`),body=encodeURIComponent(`${en?'Hello':'Bonjour'},\n\n${en?'I would like to apply as a volunteer expert for the GMA Delphi protocol.':'Je souhaite proposer ma candidature comme expert volontaire pour le protocole Delphi GMA.'}\n\n${en?'Name':'Nom'} : ${name}\nEmail : ${email}\n${en?'Field of expertise':'Domaine d’expertise'} : ${expertise}\n${en?'Sites of interest':'Sites d’intérêt'} : ${sites|| (en?'Not specified':'Non précisé')}\n\n${en?'Kind regards':'Cordialement'},\n${name}`);window.location.href=`mailto:forestecolo@gmail.com?subject=${subject}&body=${body}`;const f=document.getElementById('delphi-feedback');if(f)f.textContent=t('communication_ready');}

document.addEventListener('DOMContentLoaded',()=>{setLang(currentLang);showPage('accueil');renderSiteCatalog();renderHeroStats();populatePublishedSites();});
